scrape_configs:
  - job_name: 'ShootingResultTrackerMetrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['host.docker.internal:8881']
        labels:
          application: 'Shooting Result Tracker Application'