version: '3'

services:
  srt-postgres-database:
    container_name: srt-database
    image: postgres:15-alpine3.17
    restart: always
    ports:
      - 5433:5432
    volumes:
      - ./data/postgresDB/:/var/lib/postgresql/data
      - ./config/init/:/docker-entrypoint-initdb.d
    env_file:
      - ./postgres.env
