server:
  port: ${APP_PORT}

srt:
  security:
    jwt:
      token:
        algorithm:
          secret: ${JWT_SECRET}

spring:

  datasource:
    url: jdbc:${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA}
        dialect: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: none